spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: db-postgresql, oauth-github, oauth-acme
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      location: ${user.dir}/files/temp
logging:
  level:
    org:
      springframework: DEBUG
server:
  port: 8080
